#!/bin/sh
# Build a standalone binary with PyInstaller.
# Uses a project venv so no system pip/pyinstaller needed (works on Arch etc.).
# Output: dist/sinkswitch

set -e
cd "$(dirname "$0")"
APP_DIR="$(pwd)"
VENV_DIR="${APP_DIR}/.venv-build"

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating build venv at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
fi
echo "Using venv: $VENV_DIR"
"$VENV_DIR/bin/pip" install -q pyinstaller
# App deps so PyInstaller can trace and bundle them (yaml, PyQt6, etc.)
"$VENV_DIR/bin/pip" install -q -r requirements.txt

# Version from git tag (e.g. v0.7.12 -> 0.7.12) so the binary reports the release version
VERSION="$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")"
printf '# Generated by build.sh from git tag.\n__version__ = "%s"\n' "$VERSION" > "${APP_DIR}/src/_version.py"

"$VENV_DIR/bin/python" -m PyInstaller run_app.spec

echo ""
echo "Done. Binary: dist/sinkswitch"
echo "Run: ./dist/sinkswitch"
echo "Or move dist/sinkswitch to your PATH or Desktop."
