#!/bin/sh
# Build a standalone binary with PyInstaller.
# Uses a project venv so no system pip/pyinstaller needed (works on Arch etc.).
# Output: dist/sinkswitch (onefile) or dist/sinkswitch/ (folder; ./build.sh --onedir)

set -e
cd "$(dirname "$0")"
APP_DIR="$(pwd)"
VENV_DIR="${APP_DIR}/.venv-build"

ONEDIR=0
for arg in "$@"; do
	case "$arg" in
		--onedir) ONEDIR=1 ;;
	esac
done

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating build venv at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
fi
echo "Using venv: $VENV_DIR"
# Use python -m pip so a moved/renamed project dir does not break (pip's shebang is absolute).
"$VENV_DIR/bin/python" -m pip install -q pyinstaller
# App deps so PyInstaller can trace and bundle them (yaml, PyQt6, etc.)
"$VENV_DIR/bin/python" -m pip install -q -r requirements.txt

# Version from git tag (e.g. v0.7.12 -> 0.7.12) so the binary reports the release version
VERSION="$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")"
printf '# Generated by build.sh from git tag.\n__version__ = "%s"\n' "$VERSION" > "${APP_DIR}/src/_version.py"

if [ "$ONEDIR" -eq 1 ]; then
	export SINKSWITCH_ONEDIR=1
fi
"$VENV_DIR/bin/python" -m PyInstaller run_app.spec

echo ""
if [ "$ONEDIR" -eq 1 ]; then
	echo "Done. Portable folder: dist/sinkswitch/"
	echo "Run: ./dist/sinkswitch/sinkswitch"
	echo "See packaging/README.md for onefile vs onedir vs venv install."
else
	echo "Done. Binary: dist/sinkswitch"
	echo "Run: ./dist/sinkswitch"
	echo "Or move dist/sinkswitch to your PATH or Desktop."
fi
